class/urls.py
from django.urls import path
from . import views

app_name = "class"
urlpatterns = [
    path("", views.home, name='home'),
    path("addstudent", views.addstudent, name='add-student'),
    path("viewdata", views.viewdata, name='view-data'),
    path("about", views.about, name='about'),
    path("delete/<id>", views.delete, name='delete'),
    path("insert", views.insert, name='insertdata'),
    path("edit/<id>", views.edit, name='edit'),
    path("sliders", views.sliders, name='slider'),
    path("search/", views.search, name='search'),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("class.urls"))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

class/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100, blank=False)
    email = models.EmailField()
    age = models.IntegerField()
    image = models.ImageField(upload_to='images', default='profile.png')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Teacher(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(default="Web development teacher")

    def __str__(self):
        return self.name

class Slider(models.Model):
    text1 = models.CharField(max_length=100)
    text2 = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images', default='profile.png')

    def __str__(self):
        return self.text1

student/models.py
from django.db import models

# Create your models here.

class/views.py
from django.shortcuts import render, redirect
from .models import Student, Slider
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.
def home(request):
    data = Student.objects.all()

    return render(request, 'home.html', {'navbar': 'home', 'data': data})

def addstudent(request):
    return render(request, 'addstudent.html', {'navbar': 'add'})

def viewdata(request):
    paginator = Paginator(Student.objects.all(), 5)
    new_page = request.GET.get('page')
    student = paginator.get_page(new_page)
    return render(request, 'viewdata.html', {'navbar': 'data', 'data': student})

def about(request):

    return render(request, 'about.html', {'navbar': 'about'})


def delete(request, id):
    student = Student.objects.get(id=id)
    student.delete()
    return redirect("/viewdata")

def insert(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        email = request.POST.get("email")
        age = request.POST.get("age")
        if len(request.FILES["image"]) != 0:
            image = request.FILES["image"]

        room = Student(name=name, email=email, age=age, image=image)
        room.save()
        messages.success(request, 'Data added successfully')
        return redirect("/viewdata")
    return redirect("/viewdata")


def edit(request, id):
    std = Student.objects.get(id=id)
    cont = {'ids': std}
    if request.method == 'POST':
        name = request.POST.get("name")
        email = request.POST.get("email")
        age = request.POST.get("age")
        student = Student.objects.get(id=id)

        if len(request.FILES) != 0:
            if student.image > 0:
                student.image = request.FILES['image']

        student.name = name
        student.email = email
        student.age = age

        student.save()
        messages.warning(request, 'Data edited successfully')
        return redirect("/viewdata")
    return render(request, 'edit.html', cont)


def sliders(request):
    slide = Slider.objects.all()
    return render(request, 'slider.html', {'slider': slide, 'navbar': 'slide'})


def search(request):
    if request.method == 'GET':
        query = request.GET.get('query')
        if query:
            std = Student.objects.filter(Q(name__icontains=query) | Q(email__icontains=query) | Q(age__icontains=query))
            return render(request, 'search.html', {'data': std, 'query': query})
    return render(request, 'search.html')

student/views.py
from django.shortcuts import render

# Create your views here.

class/templates/about.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}

    <h1>About</h1>
    <img src="{% static 'images/about.jpg' %}" alt="Solar system" width="100%">
{% endblock %}

class/templates/addstudent.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}

    <div class="container">
        <h1 class="mt-5" >Add Student</h1>
        <form action="/insert" enctype="multipart/form-data" method="post" class="mt-5 px-5">

            {% csrf_token %}
            <div class="mb-3">
              <label for="name" class="form-label">Name</label>
              <input type="text" class="form-control" id="name" placeholder="Name" name="name" required>
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Email address</label>
              <input type="email" class="form-control" id="email" placeholder="name@example.com" name="email" required>
            </div>
            <label for="age" class="form-label">Age</label>
            <input type="number" id="age" class="form-control" aria-describedby="passwordHelpBlock" name="age" required>
            <div class="mb-3">
              <label for="image" class="form-label">Image</label>
              <input class="form-control" type="file" id="image" accept="image/jpeg" name="image">
                <div class="d-grid gap-2 col-6 mx-auto">
                    <button class="btn btn-primary mt-5" type="Submit">Submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

class/templates/edit.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}

    <div class="container">
        <h1 class="mt-5" >Edit Student</h1>
        <form action="/edit/{{ ids.id }}" enctype="multipart/form-data" method="post" class="mt-5 px-5">

            {% csrf_token %}
            <div class="mb-3">
              <label for="name" class="form-label">Name</label>
              <input type="text" class="form-control" value="{{ ids.name }}" id="name" placeholder="Name" name="name" required>
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Email address</label>
              <input type="email" class="form-control" id="email" value="{{ ids.email }}" placeholder="name@example.com" name="email" required>
            </div>
            <label for="age" class="form-label">Age</label>
            <input type="number" id="age" class="form-control" value="{{ ids.age }}" aria-describedby="passwordHelpBlock" name="age" required>
            <div class="mb-3">
              <label for="image" class="form-label">Image</label>
                <hr>
                <img src="../media/{{ ids.image }}" width="200" height="200" alt="{{ ids.image }}">
                <br><br>
              <input class="form-control" type="file" id="image" name="image">
                <hr>

                <div class="d-grid gap-2 col-6 mx-auto">
                    <button class="btn btn-primary mt-5" type="Submit">Submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

class/templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}
<h1>Home</h1>
{#    {% for data in data %}#}
{#        <h1>{{ data.name }}</h1>#}
{#    {% endfor %}#}
<img src="{% static 'images/home.jpg' %}" alt="Artificial Intelligence" width="100%">

{% endblock %}

class/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'images/AI.jpg' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>School</title>
</head>
<body class="bg-dark">

<div class="head">
    <a class="{% if navbar == 'home' %} tab {% endif %}" href="{% url 'class:home' %}">Home</a>
    <a class="{% if navbar == 'about' %} tab {% endif %}" href="{% url 'class:about' %}">About</a>
    <a class="{% if navbar == 'add' %} tab {% endif %}" href="{% url 'class:add-student' %}">Add Student</a>
    <a class="{% if navbar == 'data' %} tab {% endif %}" href="{% url 'class:view-data' %}">View data</a>
    <a class="{% if navbar == 'slide' %} tab {% endif %}" href="{% url 'class:slider' %}">Slider</a>
      <form class="d-flex" method="get" role="search" action="{% url 'class:search' %}">
        <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
</div>
{% block body %}


{% endblock %}
</body>
</html>

class/templates/search.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
<div class="container">
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{ message }}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
    <table class="table mt-5 tbl">
        <h1>Students - Tabular</h1>
    {% if data %}
        <h3 style="color:#c51414;">Search results for {{ query }}</h3>
    {% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{ message }}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Age</th>
          <th scope="col">Image</th>
            <th scope=col">Edit</th>
            <th scope=col">Delete</th>
        </tr>
      </thead>
      <tbody>
      {% for dd in data %}
        <tr>
          <th scope="row">{{ dd.id }}</th>
          <td>{{ dd.name }}</td>
          <td>{{ dd.email }}</td>
          <td>{{ dd.age }}</td>
          <td><img src="/media/{{ dd.image }}" alt="{{ dd.name }}" width="100", height="100"></td>
            <td>
                <a class="btn btn-warning" href="/edit/{{ dd.id }}">Edit</a>
            </td>
            <td>
                <a class="btn btn-danger" href="/delete/{{ dd.id }}">Delete</a>
            </td>

        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p><strong>No records found</strong></p>
        <img src="{% static 'images/result.png' %}" alt="No records">
    {% endif %}
    <h1>Students - Grid</h1>
    {% if data %}
        <h3 style="color:#c51414;">Search results for {{ query }}</h3>
    <div class="row">
    {% for dd in data %}

            <div class="card col-md-4 mx-3 mt-5" style="width: 18rem;">
              <img src="/media/{{ dd.image }}" class="card-img-top" alt="{{ dd.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ dd.name }}</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">{{ dd.created_at }}</a>
                </div>
        </div>
    {% endfor %}
    </div>
    {% else %}
    <p><strong>No records found</strong></p>
        <img src="{% static 'images/result.png' %}" alt="No records">
    {% endif %}
</div>
{% endblock %}

class/templates/slider.html
{% extends 'layout.html' %}
{% block body %}
{#<div id="carouselExampleDark" class="carousel carousel-dark slide">#}
{#  <div class="carousel-indicators">#}
{#    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>#}
{#    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>#}
{#    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>#}
{#      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 4"></button>#}
{#      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 5"></button>#}
{#  </div>#}
{#  <div class="carousel-inner">#}
{#      {% for txt in slider %}#}
{#            <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}" data-bs-interval="10000">#}
{#              <img src="media/{{ txt.image }}" class="d-block w-100" height="700" width="70%" alt="{{ txt.text1 }}">#}
{#              <div class="carousel-caption d-none d-md-block">#}
{#                <h3>{{ txt.text1 }}</h3>#}
{#                <p>{{ txt.text2 }}</p>#}
{#              </div>#}
{#            </div>#}
{#      {% endfor %}#}
{##}
{#  </div>#}
{#  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">#}
{#    <span class="carousel-control-prev-icon" aria-hidden="true"></span>#}
{#    <span class="visually-hidden">Previous</span>#}
{#  </button>#}
{#  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">#}
{#    <span class="carousel-control-next-icon" aria-hidden="true"></span>#}
{#    <span class="visually-hidden">Next</span>#}
{#  </button>#}
{#</div>#}
    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
      {% for txt in slider %}
    <div class="carousel-item active" data-bs-interval="1000">
      <img src="media/{{ txt.image }}"  height="100%" class="d-block w-100" alt="{{ txt.text1 }}">
        <div class="carousel-caption d-none d-md-block">
        <h3>{{ txt.text1 }}</h3>
        <p>{{ txt.text2 }}</p>
    </div>
  </div>
      {% endfor %}
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
    </div>
</div>
{% endblock %}

class/templates/viewdata.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
<div class="container">
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{ message }}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
    <table class="table mt-5 tbl">
        <h1>Students - Tabular</h1>
    {% if data %}
    {% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{ message }}</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Age</th>
          <th scope="col">Image</th>
            <th scope=col">Edit</th>
            <th scope=col">Delete</th>
        </tr>
      </thead>
      <tbody>
      {% for dd in data %}
        <tr>
          <th scope="row">{{ dd.id }}</th>
          <td>{{ dd.name }}</td>
          <td>{{ dd.email }}</td>
          <td>{{ dd.age }}</td>
          <td><img src="media/{{ dd.image }}" alt="{{ dd.name }}" width="100", height="100"></td>
            <td>
                <a class="btn btn-warning" href="/edit/{{ dd.id }}">Edit</a>
            </td>
            <td>
                <a class="btn btn-danger" href="/delete/{{ dd.id }}">Delete</a>
            </td>

        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p><strong>No records found</strong></p>
        <img src="{% static 'images/norecords.png' %}" alt="No records">
    {% endif %}
    <h1>Students - Grid</h1>
    {% if data %}
    <div class="row">
    {% for dd in data %}

            <div class="card col-md-4 mx-3 mt-5" style="width: 18rem;">
              <img src="media/{{ dd.image }}" class="card-img-top" alt="{{ dd.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ dd.name }}</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">{{ dd.created_at }}</a>
                </div>
        </div>
    {% endfor %}
    </div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center mt-5">



{% if data.has_previous %}
	<li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>

	<li class="page-item"><a class="page-link" href="?page={{ data.previous_page_number }}">Previous</a></li>

{% endif %}


<li class="page-item disabled"><a href="#" class="page-link">Page {{ data.number }} of {{ data.paginator.num_pages }}</a></li>


{% for i in nums %}
	<li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>

{% endfor %}


{% if data.has_next %}
	<li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}">Next</a></li>

	<li class="page-item"><a class="page-link" href="?page={{ data.paginator.num_pages }}">Last &raquo</a></li>

{% endif %}

 </ul>
</nav>
</div>
    {% else %}
    <p><strong>No records found</strong></p>
        <img src="{% static 'images/norecords.png' %}" alt="No records">
    {% endif %}
{% endblock %}